# For an example of go to Crawling Configuration Options at https://github.com/webrecorder/browsertrix-crawler
# Example config for a full ICAEW.com crawl. Whether it is a logged-in session is defined within the crawl profile.
# This crawl will read the seedFile.txt and only crawl 1 hop from the seed URLs.

# Basic setup
profile: /crawls/profiles/profile.tar.gz
seedFile: /app/seedFile.txt
# Collection name should be 'icaew-com-logged-in' or 'icaew-com-public'
collection: icaew-com-logged-in
screencastPort: 9037
customBehaviors: /custom-behaviors/

# Additional options
allowHashUrls: true
# combineWARC: true
# generateWACZ: true
workers: 8
text:
  - to-warc
  - to-pages
screenshot: view
diskUtilization: 0

# Crawl specific options
depth: 1  # Limit crawl to 1 hop from seed URLs
scopeType: "custom"
include:
  - ^(http(s)?:\/\/)?(www\.)?(careers\.|cdn\.|regulation\.)?icaew\.com.*$ # scope in icaew.com, careers.icaew.com, cd.icaew.com, and regulation.icaew.com
  - ^(http(s)?:\/\/)?(www\.)?(train|volunteer)\.icaew\.com(\/)?(blog.*)?$ # scope in parent and blog pages only
exclude:
  - ^.*(l|L)(o|O)(g|G)(o|O)(f|F)(f|F).*$ # block logout URLs
  - ^(http(s)?:\/\/)?(www\.)?icaew\.com\/search.*$ # block search pages (robots.txt)
  - ^(http(s)?:\/\/)?(www\.)?.*\/member(s|ship)\/active-members.*$ # block active-members pages and media files
  - ^(http(s)?:\/\/)?(www\.)?.*sprint-test-pages.*$ # block sprint-test-pages
